# Generated by Django 2.0.2 on 2018-06-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
